import { FunctionComponent, ReactNode } from "react";
import { Footer } from "./Footer/Footer";
import { Header } from "./Header/Header";
import { Sidebar } from "./Sidebar/Sidebar";

import classes from "./Layout.module.scss";
import Head from "next/head";

type LayoutProps = {
  children: ReactNode;
};

const Layout = ({ children }: LayoutProps) => {
  console.log(classes.layoutContent, "classes.layoutContent");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={classes.layoutContent}>
        <Header className={classes.header} />
        <Sidebar className={classes.sidebar} />
        <div className={classes.main}>{children}</div>
        <Footer className={classes.footer} />
      </div>
    </>
  );
};

export const withLayout = <T extends Record<string, unknown>>(
  Comment: FunctionComponent<T>
) => {
  return function withLayoutComponent(props: T) {
    return (
      <Layout>
        <Comment {...props} />
      </Layout>
    );
  };
};
